### PR TITLE
Add progressbars for scores

### PR DESCRIPTION
**Pull request by csdodd**
screenshot_1496952152

Not perfect UI, but it'll do for now.

### CODE REVIEW

**Comment by martintoften** [comment]
Nice! I thought we could make a list of all categories (Housing etc) and open a new activity with more details when we click on them
Here we have a lot of useful info: https://api.teleport.org/api/urban_areas/slug:oslo/details/

Instead a show/hide info like they do here: https://teleport.org/cities/tartu, we can do even more fancy ui

**Comment by csdodd** [comment]
Sounds good! I think we can keep these progress bars for now and make the whole category clickable to get more info.

**Comment by martintoften** [comment]
Wouldn't it be nice to tap at `Housing` and only see data about housing? I think we can do some fancy stuff if we separate it instead of throwing a lot of data into one single view. What do you think?

**Comment by martintoften** [comment]
Is it an idea to make something in Sketch for this?

**Comment by csdodd** [comment]
I was just basically copying the website, whereby you get the "score" view on the main page; and then you can click for more info.

I don't think we should worry so much about design right now. We should implement it and then get a designer involved.

**Review by martintoften — APPROVED** [review]

**Pull request merged**
